import os

def create_resume_pdf(filename="public/resume.pdf"):
    pdf_content = (
        "%PDF-1.4\n"
        "1 0 obj\n"
        "<< /Type /Catalog /Pages 2 0 R >>\n"
        "endobj\n"
        "2 0 obj\n"
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>\n"
        "endobj\n"
        "3 0 obj\n"
        "<< /Type /Page /Parent 2 0 R /Resources 4 0 R /MediaBox [0 0 612 792] /Contents 5 0 R >>\n"
        "endobj\n"
        "4 0 obj\n"
        "<< /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\n"
        "/F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\n"
        "/F3 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique >> >> >>\n"
        "endobj\n"
        "5 0 obj\n"
        "<< /Length 2200 >>\n"
        "stream\n"
        "BT\n"
        "# Header Title\n"
        "/F1 22 Tf\n"
        "50 740 Td\n"
        "(RAUNAK SHRIVASTVA) Tj\n"
        "0 -24 Td\n"
        "/F1 12 Tf\n"
        "(AI ENGINEER // DEEP LEARNING & LLM SYSTEMS) Tj\n"
        "0 -16 Td\n"
        "/F2 9 Tf\n"
        "(Email: raunakxshrivastva@gmail.com  |  GitHub: github.com/raunakxshrivastva  |  Location: India) Tj\n"
        "0 -12 Td\n"
        "(LinkedIn: linkedin.com/in/raunakxshrivastva  |  Portfolio: http://localhost:3000) Tj\n"
        "0 -20 Td\n"
        "# Divider Line\n"
        "0 -10 Td\n"
        "/F1 12 Tf\n"
        "(=================================================================================) Tj\n"
        "0 -18 Td\n"
        "/F1 12 Tf\n"
        "(EXECUTIVE SUMMARY) Tj\n"
        "0 -14 Td\n"
        "/F2 9.5 Tf\n"
        "(AI/ML Engineer with 4+ years of hands-on experience building scalable deep learning systems,) Tj\n"
        "0 -12 Td\n"
        "(LLM fine-tuning pipelines, model quantization (LoRA / GGUF), RAG architectures, and C++/CUDA) Tj\n"
        "0 -12 Td\n"
        "(performance acceleration. Passionate about stoic engineering and robust system design.) Tj\n"
        "0 -22 Td\n"
        "/F1 12 Tf\n"
        "(EDUCATION) Tj\n"
        "0 -14 Td\n"
        "/F1 10 Tf\n"
        "(B.Tech in Computer Science & Engineering) Tj\n"
        "0 -12 Td\n"
        "/F3 9 Tf\n"
        "(JECRC University, Jaipur, India  |  2022 - 2026) Tj\n"
        "0 -12 Td\n"
        "/F2 9 Tf\n"
        "(Specialization: Artificial Intelligence, Machine Learning & Neural Architectures) Tj\n"
        "0 -22 Td\n"
        "/F1 12 Tf\n"
        "(CORE TECHNICAL SKILLS) Tj\n"
        "0 -14 Td\n"
        "/F1 9.5 Tf\n"
        "(AI & Deep Learning: ) Tj\n"
        "105 0 Td\n"
        "/F2 9.5 Tf\n"
        "(PyTorch, Transformers, LangChain, Autograd Tensors, RLHF, RAG) Tj\n"
        "-105 -12 Td\n"
        "/F1 9.5 Tf\n"
        "(Programming Languages: ) Tj\n"
        "105 0 Td\n"
        "/F2 9.5 Tf\n"
        "(Python, C, C++, CUDA, JavaScript, SQL, HTML5 / CSS3) Tj\n"
        "-105 -12 Td\n"
        "/F1 9.5 Tf\n"
        "(Systems & DevOps: ) Tj\n"
        "105 0 Td\n"
        "/F2 9.5 Tf\n"
        "(Linux (POSIX Shell), Docker, Git, GitHub Actions CI/CD) Tj\n"
        "-105 -12 Td\n"
        "/F1 9.5 Tf\n"
        "(Data Science & Web: ) Tj\n"
        "105 0 Td\n"
        "/F2 9.5 Tf\n"
        "(Pandas, Scikit-Learn, Matplotlib, React.js, Next.js) Tj\n"
        "-105 -22 Td\n"
        "/F1 12 Tf\n"
        "(PROJECT HIGHLIGHTS) Tj\n"
        "0 -14 Td\n"
        "/F1 10 Tf\n"
        "(1. LLM Parameter-Efficient Fine-Tuning Engine) Tj\n"
        "0 -12 Td\n"
        "/F2 9 Tf\n"
        "(- Engineered custom LoRA & QLoRA quantization pipelines for 7B+ parameter open-source LLMs.) Tj\n"
        "0 -12 Td\n"
        "(- Reduced GPU VRAM memory overhead by 65% while maintaining benchmark task performance.) Tj\n"
        "0 -16 Td\n"
        "/F1 10 Tf\n"
        "(2. CUDA-Accelerated Tensor Matrix Multiplication Kernel) Tj\n"
        "0 -12 Td\n"
        "/F2 9 Tf\n"
        "(- Developed custom low-level C++/CUDA kernels for high-throughput parallel linear algebra execution.) Tj\n"
        "0 -12 Td\n"
        "(- Achieved 3.4x latency speedup over naive host CPU memory execution.) Tj\n"
        "0 -16 Td\n"
        "/F1 10 Tf\n"
        "(3. Roots of Gratitude — Interactive Skill Tree Visualizer) Tj\n"
        "0 -12 Td\n"
        "/F2 9 Tf\n"
        "(- Built high-definition 8K Stoic tree interactive portfolio dossier in Next.js & Framer Motion.) Tj\n"
        "0 -12 Td\n"
        "(- Implemented real-time drag-and-drop node alignment and persistent state telemetry.) Tj\n"
        "0 -22 Td\n"
        "/F1 12 Tf\n"
        "(CERTIFICATIONS & ACHIEVEMENTS) Tj\n"
        "0 -14 Td\n"
        "/F2 9 Tf\n"
        "(- 28+ Active Open Source AI Repositories on GitHub) Tj\n"
        "0 -12 Td\n"
        "(- Open for AI Consulting & Research Collaborations (2026 Active)) Tj\n"
        "ET\n"
        "endstream\n"
        "endobj\n"
        "xref\n"
        "0 6\n"
        "0000000000 65535 f \n"
        "0000000009 00000 n \n"
        "0000000058 00000 n \n"
        "0000000115 00000 n \n"
        "0000000214 00000 n \n"
        "0000000387 00000 n \n"
        "trailer\n"
        "<< /Size 6 /Root 1 0 R >>\n"
        "startxref\n"
        "2640\n"
        "%%EOF\n"
    )
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(pdf_content)
    print(f"Resume generated at {filename}")

if __name__ == "__main__":
    create_resume_pdf()
